// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_explorer = "CgkI0Ofr6sYSEAIQAg"; // <GPGSID>
        public const string achievement_revival = "CgkI0Ofr6sYSEAIQBA"; // <GPGSID>
        public const string achievement_hunter = "CgkI0Ofr6sYSEAIQAw"; // <GPGSID>
        public const string achievement_easy_game = "CgkI0Ofr6sYSEAIQBw"; // <GPGSID>
        public const string achievement_baka = "CgkI0Ofr6sYSEAIQBQ"; // <GPGSID>
        public const string achievement_treasures_tracker = "CgkI0Ofr6sYSEAIQAQ"; // <GPGSID>
        public const string achievement_dark_soul_hunter = "CgkI0Ofr6sYSEAIQBg"; // <GPGSID>

}

